### ISSUE TITLE
sync.runtime_Semacquire Issues

### ISSUE THREAD

**Issue by kashkashio** [joomcode/redispipe#10]
Hi,
I'm having an issue with this library, some times, not persistently i'm getting this errors:

`goroutine 4232873 [semacquire]:
sync.runtime_Semacquire(0xc726a19658)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc726a19650)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/joomcode/redispipe/redis.Sync.Send(0xcacd80, 0xc0001ee000, 0xbaf00e, 0x3, 0xc726731a40, 0x1, 0x1, 0x3, 0x2a)
	/home/tsah/go/src/github.com/joomcode/redispipe/redis/sync.go:26 +0xbb
github.com/joomcode/redispipe/redis.Sync.Do(...)
	/home/tsah/go/src/github.com/joomcode/redispipe/redis/sync.go:17
kashkash.com/ServingServer/routes.serverDescisionTagLoad(0xc702c1ed88, 0x3e9)
	/home/tsah/go/src/kashkash.com/ServingServer/routes/KpmClick.go:844 +0x200
kashkash.com/ServingServer/routes.serverDescision(0xc702c1ed88)
	/home/tsah/go/src/kashkash.com/ServingServer/routes/KpmClick.go:808 +0xb5
kashkash.com/ServingServer/routes.KpmClick(0xc6f471a000)
	/home/tsah/go/src/kashkash.com/ServingServer/routes/KpmClick.go:120 +0x1fa
main.main.func1(0xc6f471a000)
	/home/tsah/go/src/kashkash.com/ServingServer/app.go:346 +0x1ff
github.com/zkpmbro/fasthttp.(*Server).serveConn(0xc0000d2200, 0xcae700, 0xc51af535e0, 0x0, 0x0)
	/home/tsah/go/src/github.com/zkpmbro/fasthttp/server.go:2018 +0x6ab
github.com/zkpmbro/fasthttp.(*workerPool).workerFunc(0xc000ab5040, 0xc6f33f30e0)
	/home/tsah/go/src/github.com/zkpmbro/fasthttp/workerpool.go:212 +0xc0
github.com/zkpmbro/fasthttp.(*workerPool).getCh.func1(0xc000ab5040, 0xc6f33f30e0, 0xab4cc0, 0xc6f33f30e0)
	/home/tsah/go/src/github.com/zkpmbro/fasthttp/workerpool.go:184 +0x35
created by github.com/zkpmbro/fasthttp.(*workerPool).getCh
	/home/tsah/go/src/github.com/zkpmbro/fasthttp/workerpool.go:183 +0x10a`

Any idea? Might be related to memory exhausted ?
Thanks :)

**Comment by funny-falcon** [comment]
You hadn't wrote which error did you get. You gave only stacktrace.

**Comment by funny-falcon-at-joomcode** [comment]
Sorry, you didn't provide further details. Feel free to reopen.
