### ISSUE TITLE
Optimization for Cluster Pipeline in `SendMany` by using Batch Call to Conn

### ISSUE THREAD

**Issue by lukemin89** [joomcode/redispipe#21]
Note: there's no performance issue, and it is just a wish.

Currently, rediscluster only supports `SendMany` ([link](https://github.com/joomcode/redispipe/blob/fe5aa96112bfbdcc9040c42c7ea6812ea41955ee/rediscluster/cluster.go#L499-L503)), which under the hood, use loop + `Send`.

`SendTransaction` supports sending everything in one shot, but I don't think that is the purpose of the transaction.

I think we can group requests by slots (or node), and send them using `conn.SendBatch` as an optimization.
go-redis supports pipelining by grouping commands by node ([link](https://github.com/go-redis/redis/blob/60d62a8a40821552e86f9e99946585d266d9bda8/cluster.go#L1144-L1171)).

Please kindly instruct me if there's already a way to achieve this...

**Comment by funny-falcon** [comment]
In our setup SendMany were used just to send many requests for quite different hash tag. Therefore there was no benefit for optimizing case of same hash tag.

It is hard to optimize for both cases without api break.

If you make experiment and prove you have measurable and meaningful gain from such change, I will think about.
By meaningful I mean as least 10% of something without loose in other area, of 20% of something with slight loose in other area.

> go-redis supports pipelining by grouping commands by node

redispipe ALWAY works in pipelining mode.
But go-redis doesn't, therefore it has benefit from grouping.
