### ISSUE TITLE
Error debugging in GoLand 

### ISSUE THREAD

**Issue by kashkashio** [joomcode/redispipe#5]
Hi,
I'm using this library and i found that its really delivers what it promised to !
its fast and lightweight much more than all other Go redis lib's out there so well done for that !

Another issue i'm facing is that i'm using GoLand IDE by jetbrains, everything works well beside one thing.. when i'm running on debug and i try to debug the result i got from the redis i get an error:
redispipe.io.error

But when i'm running without debug, the same lines of code works perfectly.
I Tried moving the context and the whole connection to global var and many other options but was unable to Debug the result...

Plus i tried using SyncCtx and normal Sync and yet same behaviour :(

Any idea ? how to overcome it ?
Because its pretty basic for me to be able to debug what comes back from redis "get".

Thanks a lot and keep up with the awesome work !

**Comment by kashkashio** [comment]
Really? nothing?

**Comment by funny-falcon-at-joomcode** [comment]
Sorry, I've missed this issue.

I think you hit network timeout. By default it is not zero (ie default zero is converted to 5 seconds).
Try to set IOTimeout = -1 and DialTimeout = -1 in Connext options.

**Comment by kashkashio** [comment]
Worked like a charm ! Well done :D Thanks a lot you are a life saver!
